name: generate-keywords-usgs
run-name: Generating USGS keywords ${{ github.ref_name }}
on:
  push
  # schedule:
  #   - cron: "40 7 * * *"
  #   - cron: "*/5 * * * *"
env:
  CONF_JSON: "src/usgs/conf.json"
jobs:
  generate-json-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Running nightly build
        run: date
      - name: Install node packages
        run: npm i
        working-directory: ./harvesters
      - name: Run script to generate new files
        run: node src/usgs/index.js
        working-directory: ./harvesters
      - name: Configure git user
        run: git config --local user.name actions-user
      - name: Configure git user's email
        run: git config --local user.email actions@github.com
      - name: Update repo
        run: git pull
      - name: Add resource(s) to commit
        run: git add resources/json/*
      - name: Git Status
        id: git-status
        run: |
          GIT_STATUS = git status | tail -1
          echo $GIT_STATUS
          Write-Host "::set-output name=git_status::$GIT_STATUS"
      - name: Commit new resource(s)
        if: steps.git-status.outputs.git_status != 'nothing to commit, working tree clean'
        run: git commit -m "Updating resource(s)"
      - name: Push results
        run: git push -f origin ${{ github.ref_name }}
